### ISSUE TITLE
How to call download report.json file by click on a custom button?

### ISSUE THREAD

**Issue by nbarman760** [WebDataRocks/pivot-react#1]

**Comment by tsshn** [comment]
Hello,

Thank you for your question.

Such functionality is achievable using the `save` API call. More information about the method can be found by the link:  [Save API call](https://www.webdatarocks.com/doc/save/).

Please check out [an example we have prepared](https://codepen.io/webdatarocks/pen/jOEweqm) for you.

Regards,
Illia
