### ISSUE TITLE
getreports() method not working giving errors

### ISSUE THREAD

**Issue by kalimuthu123** [WebDataRocks/pivot-react#12]
![error](https://user-images.githubusercontent.com/42966797/71091599-61bbd980-21cb-11ea-9334-10a569feac64.png)
![error1](https://user-images.githubusercontent.com/42966797/71091657-82842f00-21cb-11ea-989a-700a8e00d71b.png)

**Comment by tsshn** [comment]
Hello,

Thank you for connecting us.

Our team did not manage to reproduce the error while calling the `getReport` method.

It would be very useful for our investigation if you could provide steps that lead to an error in the browser's console and describe the context of using the `getReport` API call.

Regards,
Illia
