### ISSUE TITLE
Table not updating when data is updated

### ISSUE THREAD

**Issue by pbischoff** [WebDataRocks/pivot-react#73]
I'm using the pivot table to show some data from the backend. I have implemented a filter function, which filters the data passed to my `PivotTable` component e.g., by year or name.

However, even though the props for `PivotTable` and the `data` state changes and triggers a re-rendering of the entire component, the browser still shows the entire data, not the filtered data. Only if the hot reloading is triggered, the table actually updates.

Here is my `PivotTable` component:
```
import React, { useState, useEffect } from 'react';
import { Pivot } from "@webdatarocks/react-webdatarocks";

const PivotTable = ({ tableData }) => {
  const [data, setData] = useState(tableData);

  useEffect(() => {
    setData(tableData);
  }, [tableData]);

  return (
    <div>
      <Pivot
        toolbar={false}
        report={data}
      />
    </div>
  )
}

export default PivotTable;
```

**Comment by maksymkaD** [comment]
Hello,

Thank you for writing to us.

In your current implementation, you are only updating the local state of your PivotTable component when the `tableData` prop changes. However, this doesn't update the data in the pivot table itself.

To update the data in the pivot table, you should use the `updateData` API call provided by WebDataRocks. This method allows you to update the data in the pivot table without reloading the entire component.

Here is how you can modify your PivotTable component to use the `updateData` method:

```
import React, { useEffect, useRef } from 'react';
import { Pivot } from "@webdatarocks/react-webdatarocks";

const PivotTable = ({ tableData }) => {
  const pivotRef = useRef(null);

  useEffect(() => {
    if (pivotRef.current) {
      pivotRef.current.webdatarocks.updateData({ data: tableData });
    }
  }, [tableData]);

  return (
    <div>
      <Pivot
        ref={pivotRef}
        toolbar={false}
        report={{ dataSource: { data: tableData } }}
      />
    </div>
  )
}

export default PivotTable;
```

Hope this helps.

Best Regards,
